#The data of objects except 'static' objects' is here.

data={
    #BACKGROUND
    0:{
        'TYPE': 'BACKGROUND',
        'PATH': 'pic/other/back.png',
        'INDEX': 0,
        'INDEX_CNT': 0,
        'SIZE': (1650,600),
        'POS_TIME': 0,
        'INDEX_TIME': 0,
        'SUMMON_TIME': -1,
        'SPEED_L': 0,
        'SPEED_R': 0,
        'SPEED_U': 0,
        'SPEED_D': 0,
        'HAS_SUMMON':False,
        'CAN_LOOT':False,
        'PRICE': -1,
        'HP': -1,
        'ATTACK': -1,
    },

    #NORMAL ZOMBIE
    1:{
        'TYPE': 'NORM_ZOMBIE',
        'PATH': 'pic/zombie/0/%d.png',
        'INDEX': 0,
        'INDEX_CNT': 15,
        'SIZE': (100,128),
        'POS_TIME': 0.2,
        'INDEX_TIME': 0.2,
        'SUMMON_TIME': -1,
        'SPEED_L': 2.4,
        'SPEED_R': 0,
        'SPEED_U': 0,
        'SPEED_D': 0,
        'HAS_SUMMON':False,
        'CAN_LOOT':False,
        'PRICE': -1,
        'HP': 6,
        'ATTACK': 1,
    },

    #NORMAL SUNFLOWER
    2:{
        'TYPE': 'NORM_SUNFLOWER',
        'PATH': 'pic/plant/sunflower/%d.png',
        'INDEX': 0,
        'INDEX_CNT': 18,
        'SIZE': (125,125),
        'POS_TIME': 0.06,
        'INDEX_TIME': 0.1,
        'SUMMON_TIME': 8,
        'SPEED_L': 0,
        'SPEED_R': 0,
        'SPEED_U': 0,
        'SPEED_D': 0,
        'HAS_SUMMON':True,
        'CAN_LOOT':False,
        'PRICE': 50,
        'HP': 1500,
        'ATTACK': 0,
    },

    #NORMAL PEABULLET
    3:{
        'TYPE': 'NORM_PEABULLET',
        'PATH': 'pic/other/peabullet.png',
        'INDEX': 0,
        'INDEX_CNT': 0,
        'SIZE': (25,25),
        'POS_TIME': 0.008,
        'INDEX_TIME': 0.2,
        'SUMMON_TIME': -1,
        'SPEED_L': 0,
        'SPEED_R': 4,
        'SPEED_U': 0,
        'SPEED_D': 0,
        'HAS_SUMMON':False,
        'CAN_LOOT':False,
        'PRICE': -1,
        'HP': 1,
        'ATTACK': 1,
    },

    #SUNSHINE
    4:{
        'TYPE': 'SUNSHINE',
        'PATH': 'pic/sunshine/%d.png',
        'INDEX': 0,
        'INDEX_CNT': 30,
        'SIZE': (100,100),
        'POS_TIME': 0.02,
        'INDEX_TIME': 0.02,
        'SUMMON_TIME': -1,
        'SPEED_L': 0,
        'SPEED_R': 0,
        'SPEED_U': 3.2,
        'SPEED_D': 1,
        'INTERVAL_SUMMON_SUNFLOWER': 9,
        'INTERVAL_DOWN': 15,
        'HAS_SUMMON':False,
        'CAN_LOOT':True,
        'PRICE': 25,
        'HP': -1,
        'ATTACK': -1,
    },

    #NORMAL PEASHOOTER
    5:{
        'TYPE': 'NORM_PEASHOOTER',
        'PATH': 'pic/plant//peashooter/%d.png',
        'INDEX': 0,
        'INDEX_CNT': 14,
        'SIZE': (115,115),
        'POS_TIME': 0.02,
        'INDEX_TIME': 0.2,
        'SUMMON_TIME': 3,# Actually this is useless because the summoning of peabullet is controlled by the peashooter.
        'SPEED_L': 0,
        'SPEED_R': 0,
        'SPEED_U': 0,
        'SPEED_D': 0,
        'HAS_SUMMON':True,
        'CAN_LOOT':False,
        'PRICE': 100,
        'HP': 1500,
        'ATTACK': 0,
    }
}